Should FIX #12 (test if tmp/boundary/ exists)
Should partially FIX #15, 5 countries are commented because :

British Sovereign Base Areas doesn't have any ISO code

Germany, Russia, Ukraine and Belarus cause this error :
asyncpg.exceptions.InternalServerError: lwpoly_from_lwlines: shell must
be closed